### ISSUE TITLE
Date is always reported as May 21st, 2020

### ISSUE THREAD

**Issue by boucur** [jdlrobson/WikiLovesINat#11]
Whichever photo I select to import from iNaturalist to Commons, it says: `  |date=2020-5-21`. The date should instead be the "Observed Date", right? For example for this https://www.inaturalist.org/photos/72062705 it would be 2020-05-29?

(Also, the months and days should have a leading 0 when appropriate - I kept getting bot date fixes after importing, e.g. it would change `2020-5-21` to `2020-05-21`.)

**Comment by jdlrobson** [comment]
will look into this within the next week. Sorry for the delayed response here.

I think the date being reported is today's date
