### ISSUE TITLE
Ability to upload iNaturalist pictures by iNat user id and/or observation id

### ISSUE THREAD

**Issue by codrinbucur** [jdlrobson/WikiLovesINat#12]
Hi,

This is a great tool and initiative!

But it would be great if you could provide a way to upload iNaturalist pictures by user id or observation id.

I would like to select one or more observations I contributed to iNaturalist and then push them to Wikimedia Commons, using with my Wikimedia ID ideally.

Thanks
-Codrin

**Comment by jdlrobson** [comment]
will look into this within the next week. Sorry for the delayed response here.
