### ISSUE TITLE
Only show images with verified identifications

### ISSUE THREAD

**Issue by kaldari** [jdlrobson/WikiLovesINat#7]
In inat.js, you should replace "verifiable=true" with "quality_grade=research", so that only photos with verified identifications are shown.

**Comment by kaldari** [comment]
@jdlrobson - Any thoughts about this?

**Comment by jdlrobson** [comment]
Heya! Sorry, missed this issue. Will take a look later today.

**Comment by jdlrobson** [comment]
Fixed in https://github.com/jdlrobson/WikiLovesINat/commit/0807e01068b62fdb30b9997910cd8674037c9f4b

Clearly need to give the issues here some more love!
